# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 424ff7290a797021123443913c74d9c1da3d8324f264571ece242a27cdd8ff0dda5d04961189207af7079ae1cfd72f4217b1f116253c73f9b76d90606718321b

test:
  secret_key_base: 9aec2f1b9c728a8d551795d9a11409db921b74fe85f3ece845399cc72a3623dc44fd697e10de2086b5656f1ddf687e94981538e86f1acdc2b37ba6a0003fa555

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
